[stack]
name = "qwen3_5_fp8dkv"
track = "lab"
primary_service = "llm"
notes = "Minimal tool-capable Qwen3.5 multi-modal-model."

[defaults]
# host = "0.0.0.0"

[defaults.args]
dtype = "bfloat16"
load_format = "auto"
gpu_memory_utilization = 0.98
# max_num_seqs = 10

[services.llm]
engine = "vllm"
runtime_bin_dir = ".venv-vllm/bin"
model = "${QUANT_ROOT}/llm-compressor-artifacts/Qwen3.5-9B-FP8-DYNAMIC-KV-v2"
port = 8002
served_model_name = "qwen3.5_9b"
# extra_args = ["--disable-log-requests"]

[services.llm.env]
VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS = "0"
PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True"

[services.llm.args]
enable_prefix_caching = true
max_model_len = 135168
enable_auto_tool_choice = true
tool_call_parser = "qwen3_xml"
reasoning_parser = "qwen3"
exclude_tools_when_tool_choice_none = true
# performance_mode = "interactivity"
enable-force-include-usage = true
# chat_template_content_format = "openai"
# default_chat_template_kwargs = "{\"enable_thinking\":true}"
# generation_config = "auto"
# kv_cache_memory_bytes = "10466787727"
kv_cache_dtype = "fp8_e4m3"
# does not work with qwen's hybrid attention (works with omnicoder fp8 i think)
# calculate_kv_scales = true 


# limit_mm_per_prompt = "{\"image\":1}"
# language_model_only = true

[services.llm.assets]
chat_template = "assets/chat_templates/qwen3.5_hf_fix_chat_template.jinja"
